// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1nNypid8F9K3jn6gZ7ylUbGkCq4pqCc',
    appId: '1:900551396478:web:57bcc4461c020b10901c2f',
    messagingSenderId: '900551396478',
    projectId: 'astryx-app-f5678',
    authDomain: 'astryx-app-f5678.firebaseapp.com',
    storageBucket: 'astryx-app-f5678.firebasestorage.app',
    measurementId: 'G-VSN0E9G0SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDy_N-3CB0YCqQZeTyXRVflhmIMppn9Uo',
    appId: '1:900551396478:android:29854a24a19ad373901c2f',
    messagingSenderId: '900551396478',
    projectId: 'astryx-app-f5678',
    storageBucket: 'astryx-app-f5678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvIAL-PbhfQyur8rAUpD7Jy8af3-ZENxw',
    appId: '1:900551396478:ios:c0f272eab9645bb6901c2f',
    messagingSenderId: '900551396478',
    projectId: 'astryx-app-f5678',
    storageBucket: 'astryx-app-f5678.firebasestorage.app',
    iosBundleId: 'com.astryx.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvIAL-PbhfQyur8rAUpD7Jy8af3-ZENxw',
    appId: '1:900551396478:ios:fbda152faea6b4dc901c2f',
    messagingSenderId: '900551396478',
    projectId: 'astryx-app-f5678',
    storageBucket: 'astryx-app-f5678.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD1nNypid8F9K3jn6gZ7ylUbGkCq4pqCc',
    appId: '1:900551396478:web:58854e1880ecc28e901c2f',
    messagingSenderId: '900551396478',
    projectId: 'astryx-app-f5678',
    authDomain: 'astryx-app-f5678.firebaseapp.com',
    storageBucket: 'astryx-app-f5678.firebasestorage.app',
    measurementId: 'G-D386XRD5H0',
  );
}
